//
//  Definitions.swift
//  tstBt
//
//  Created by Круцких Олег on 22.11.15.
//  Copyright © 2015 Круцких Олег. All rights reserved.
//

import CoreBluetooth


let NEXX_HRM_DEVICE_INFO_SERVICE_UUID = "180A"
let NEXX_HRM_HEART_RATE_SERVICE_UUID = "180D"

let NEXX_HRM_MEASUREMENT_CHARACTERISTIC_UUID = "2A37"

let NEXX_HRM_BODY_LOCATION_CHARACTERISTIC_UUID = "2A38"
let NEXX_HRM_MANUFACTURER_NAME_CHARACTERISTIC_UUID = "2A29"

let TRANSFER_SERVICE_UUID = "E20A39F4-73F5-4BC4-A12F-17D1AD666661"